### ISSUE TITLE
Critical bug - there is a symlink, not a directory

### ISSUE THREAD

**Issue by KukyMan** [rosell-dk/webp-express#115]
**When i do the test with any binary(convertor), it throws the following warnings and no test image is there.**

> Warning: filesize(): stat failed for /var/www/junakslavicin.cz/web/../../clients/client17/web218/web/wp-content/webp-express/config/wod-options.json in /var/www/clients/client17/web218/web/wp-content/plugins/webp-express/wod/webp-on-demand.php on line 17
> 
> Warning: fread() expects parameter 1 to be resource, boolean given in /var/www/clients/client17/web218/web/wp-content/plugins/webp-express/wod/webp-on-demand.php on line 17
> 
> Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/clients/client17/web218/web/wp-content/plugins/webp-express/wod/webp-on-demand.php on line 18
> 
> Warning: Invalid argument supplied for foreach() in /var/www/clients/client17/web218/web/wp-content/plugins/webp-express/wod/webp-on-demand.php on line 27
> 
> Notice: Undefined index: forward-query-string in /var/www/clients/client17/web218/web/wp-content/plugins/webp-express/wod/webp-on-demand.php on line 38

**I figured it out.**

in _/plugins/webp-express/wod/webp-on-demand.php_, I disabled (removed) 
`$contentDirAbs = $_SERVER['DOCUMENT_ROOT'] . '/' . $_GET['wp-content'] . '/webp-express';`
instead, I hard coded the path like that – 
`$contentDirAbs = $_SERVER['DOCUMENT_ROOT'] . '/wp-content/webp-express';`

It throws the errs because /var/www/junakslavicin.com is a symlink, not a directory. Therefore, “../../” (returning the 2 directories above) does not work.

Please, make a update of the code, because this is a critical bug.

**Comment by rosell-dk** [comment]
Same issue is reported in wordpress issue queue, [here](https://wordpress.org/support/topic/error-when-converting/#post-10995211)
