### ISSUE TITLE
Alter HTML

### ISSUE THREAD

**Issue by rosell-dk** [rosell-dk/webp-express#147]
Add ability to either use picture-tag syntax or alter the image URL. With that, WebP Express can be used to serve webp conditionally without redirecting (without depending on Cache Enabler or ShortPixel to do the HTML altering). Also, it can be set up to serve webp to all browsers. This can be used in conjuction with the wonderful webpjs library that enables web

**Comment by rosell-dk** [comment]
Getting there.

1. The "AlterHtml" classes should not depend on wordpress functions. The upload url can for example be  calculated in `Config.php`, and added to the `webp-express-alter-html-options` option (in the *updateAutoloadedOptions* function)

2. The image url replacements taken from Cache Enabler should be altered to process attributes typically used for lazy loading as well ("data-lazy-src", "data-src", "data-lazy-srcset", etc)

**Comment by rosell-dk** [comment]
Also, we need to test this thoroughly.
And perhaps mark the feature as "beta"

**Comment by rosell-dk** [comment]
The feature is now marked as beta.
It has also been tested pretty thoroughly now with test cases. However, the test cases has only been run on one system

**Comment by willstocks-tech** [comment]
It would work, but the webp versions of the images do not exist. I can’t
get them to generate either :(

**Comment by rosell-dk** [comment]
In next release there is a new feature for automatically generating missing webp when they are requested

**Comment by willstocks-tech** [comment]
Ah ok that’s cool! Thanks - let me know if you need a tester!

So just to confirm - current version = only generates a webp on media
upload and everything else historic remains as is?

**Comment by rosell-dk** [comment]
Nah, not quite. Look at my explanation of current behaviour here:
https://wordpress.org/support/topic/how-does-this-work-41/

**Comment by willstocks-tech** [comment]
Ok, that makes sense! I think my issue might be a potential edge-case, related to #161!

**Comment by rosell-dk** [comment]
Turned out the problem was that webp-realizer.php wasn't working on symlinked folders. Its fixed now

**Comment by rosell-dk** [comment]
Ok, testing complete! Publishing!
