### ISSUE TITLE
Space in original filename results in 400 error

### ISSUE THREAD

**Issue by SamBenson** [rosell-dk/webp-express#164]
My site is hosted on WPEngine so I've followed the last comment on here - https://wordpress.org/support/topic/nginx-rewrite-rules-4/#post-10983806 in order to enable the plugin but I've noticed issues with conversion when the original filename has a space in it. 

Example: 
`this image.png` will result in a 400 error when viewed in the browser
`this-image.png` will work as expected

For reference, I'm using the GD conversion method for JPGs and EWWW for PNGs.

**Comment by SamBenson** [comment]
**Update**: This is a WPEngine issue. Support confirmed that filenames with a space in them will cause issues with nginx rewrites. @rosell-dk Might be an idea to update the docs with a note or something.

**Comment by SamBenson** [comment]
**Another Update:** I've updated the suggested nginx rule to ignore filenames with spaces now so that it will work to some degree on WPEngine whilst I rename any uploads, etc that contain spaces. 

```
if ($http_accept ~* "webp"){  
        rewrite ^\/(((?!\s).)*)\.(jpe?g|png)$ /wp-content/plugins/webp-express/wod/webp-on-demand.php?xsource=x$request_filename&wp-content=wp-content break;
}
```

**Comment by rosell-dk** [comment]
Hi,
Sorry, been too busy to read all incoming.

Wordpress automatically renames uploads containing spaces in the filename so it shouldn't be too big a problem. And being that the problem actually lies on WPEngine, I shall leave it there.

Btw: Note that I have updated the Nginx section in the FAQ, adding more advanced rules for better performance.
