### ISSUE TITLE
Better rules for Nginx

### ISSUE THREAD

**Issue by rosell-dk** [rosell-dk/webp-express#166]
We should provide better rules for Nginx.
The rules should redirect directly to existing webp files, and set Vary: Accept header when it does

Current rule is simply:
```nginx
if ($http_accept ~* “webp”){
  rewrite ^/(.*).(jpe?g|png)$ /wp-content/plugins/webp-express/wod/webp-on-demand.php?wp- 
 content=wp-content break;
}
```

**Comment by rosell-dk** [comment]
These redirects to existing webp. But it does not set the Vary header. Unfortunately the 'add_header' directive directive does not seem to be allowed in an `if` context inside server. The `if` context must be inside `location` according to [docs](https://nginx.org/en/docs/http/ngx_http_headers_module.html)

```
# WebP Express rules
# --------------------
if ($http_accept ~* "webp"){
  set $whattodo A;
}
if (-f $request_filename.webp) {
  set $whattodo  "${whattodo}B"; 
}
if ($whattodo = AB) {
  rewrite ^(.*) /$1.webp break;
}

if ($whattodo = A) {
  rewrite ^/(.*).(jpe?g|png)$ /wp-content/plugins/webp-express/wod/webp-on-demand.php?xsource=x$request_filename&wp-content=wp-content break;
}
```
The code must be inserted in the `server` context

I'm using [this hack](https://gist.github.com/jrom/1760790) for checking multiple `if` conditions

**Comment by rosell-dk** [comment]
Here is another way to achieve the same:

In http context (or outside server context in your host configuration file) insert:
```
map $http_accept $webp_suffix {
    default   "";
    "~*webp"  ".webp";
}
```

In `server` context insert this:

```
location ~ ^.*(png|jpe?g)$ {
  add_header Vary Accept;
  try_files
    $uri$webp_suffix
    /wp-content/plugins/webp-express/wod/webp-on-demand.php?xsource=x$request_filename&wp-content=wp-content
    ;
}
```
The solution is based on [this recipe](https://github.com/uhop/grunt-tight-sprite/wiki/Recipe:-serve-WebP-with-nginx-conditionally). But I have added the converter script in the *try_files*. Also, in order for the php to be processed, I have removed "$uri =404;" from `try_files` (got that solution [here](https://stackoverflow.com/questions/23917213/nginx-try-files-does-not-pass-to-php))

**Comment by rosell-dk** [comment]
Here is a third solution.
It contains `if` directives inside a `location` statement, which is "evil".
It however seems to work alright.
The solution is basically a modification of the first, but wrapped inside a `location`. I got to know that this was possible when viewing [the rules presented in this blog post on keycdn](https://www.keycdn.com/blog/convert-to-webp-the-successor-of-jpeg#rewriterules-for-nginx-nginx-conf))

```nginx
    # WebP Express rules
    # --------------------
    location ~* ^/wp-content/.*\.(png|jpe?g)$ {
        add_header Vary Accept;
        expires 365d;

        if ($http_accept ~* "webp"){
            set $whattodo A;
        }
        if (-f $request_filename.webp) {
            set $whattodo  "${whattodo}B";
        }
        if ($whattodo = AB) {
            rewrite ^(.*) $1.webp last;
        }
        if ($whattodo = A) {
            rewrite ^/wp-content/.*\.(jpe?g|png)$ /wp-content/plugins/webp-express/wod/webp-on-demand.php?xsource=x$request_filename&wp-content=wp-content last;
        }
    }

    location ~* ^/wp-content/.*\.webp$ {
        expires 365d;
        if ($whattodo = AB) {
            add_header Vary Accept;
        }
    }
    # ------------------- (WebP Express rules ends here)
```


For reference, the rules presented in the blog post by keycdn looks like this:

```
location ~ ^(/path/to/your/images.+)\.(jpe?g|png)$ {
    if ( $http_accept ~* webp ) {
        set $webp "A";
    }
    if ( $request_filename ~ (.+)\.(png|jpe?g)$ ) {
        set $file_without_ext $1;
    }
    if ( -f $file_without_ext.webp ) {
        set $webp "${webp}E";
    }

    if ( $webp = AE ) {
        add_header Vary Accept;
        rewrite ^(.+)\.(png|jpe?g)$ $1.webp break;
    }
}
```

**Comment by rosell-dk** [comment]
Here are rules for routing non-existing webp requests to converter:

```nginx
location ~* ^/?wp-content/.*\.(png|jpe?g)\.webp$ {
    try_files
      $uri
      /wp-content/plugins/webp-express/wod/webp-realizer.php?wp-content=wp-content
      ;
}
```
I'm getting the hang of it :)

**Comment by koekaverna** [comment]
```

**Comment by koekaverna** [comment]
Your config always run php. `$uri.webp` doesn't exist, because plugin store webp images in different than original image folder.
So I added the path to webp images directory to argument
```
# WebP Express rules
# --------------------
location ~* ^/?wp-content/.*\.(png|jpe?g)$ {
  add_header Vary Accept;
  # expires 365d;
  if ($http_accept !~* "webp"){
    break;
  }
  try_files
    /wp-content/webp-express/webp-images/doc-root/$uri.webp
    /wp-content/plugins/webp-express/wod/webp-on-demand.php?xsource=x$request_filename&wp-content=wp-content
    ;
}
# ------------------- (WebP Express rules ends here)
```

PS. I checked it with
`try_files { $uri.webp $uri.webp;}` **got 404**
and
`try_files {
    /wp-content/webp-express/webp-images/doc-root/$uri.webp
    /wp-content/webp-express/webp-images/doc-root/$uri.webp
   ;
}` **got image**

**Comment by rosell-dk** [comment]
@koekaverna: You can configure the plugin to store images in the same folder as the originals on the plugin settings screen. However, images outside of the upload folder (ie theme images) are always stored in a separate folder so your setup is better. Thanks

**Comment by rosell-dk** [comment]
When destination is set to "mingled", your modified line is needed *in addition* to the original (for theme images etc).

So that solution becomes:
```nginx
# WebP Express rules
# --------------------
location ~* ^/?wp-content/.*\.(png|jpe?g)$ {
  add_header Vary Accept;
  # expires 365d;
  if ($http_accept !~* "webp"){
    break;
  }
  try_files
    /wp-content/webp-express/webp-images/doc-root/$uri.webp
    $uri.webp
    /wp-content/plugins/webp-express/wod/webp-on-demand.php?xsource=x$request_filename&wp-content=wp-content
    ;
}
# ------------------- (WebP Express rules ends here)

When configured to store in separate folder, you can remove the line containing "$uri.webp"

**Comment by mbt1370** [comment]
i tried above all things but still it shows error for Nginx.

```
>Bummer. As the "content-type" header reveals, we got the jpeg.
It seems we can conclude that the rewrite did not happen.
In addition, we did not get a content-length header either.It seems we can conclude that the rewrite did not happen.
The test FAILED.
```

**Comment by mbt1370** [comment]
problem is solved but it not generate for lazyload images.

**Comment by formido** [comment]
> problem is solved but it not generate for lazyload images.

How was the problem solved?

**Comment by JorenRapini** [comment]
Tried these ideas but web console reports "It seems you are visiting this file (plugins/webp-express/wod/webp-on-demand.php) directly. We do not allow this." when viewing where it attempts to load the image assets
