### ISSUE TITLE
Images don't seem to be converting

### ISSUE THREAD

**Issue by willstocks-tech** [rosell-dk/webp-express#179]
hi @rosell-dk 

So, I have just updated webp express on my install and have configured as follows:
![image](https://user-images.githubusercontent.com/43744514/53103437-8dc3eb00-3525-11e9-9d8a-dacf05242fe5.png)

I have then navigated to a bunch of different images on my site (local, not S3/Cloudfront stored) to check whether the webp variants are being generated:
https://willstocks.co.uk/wp-content/uploads/2018/10/Cheerson-CX10-Review.jpg as an example.

I then changed .jpg to .webp and that failed. So I FTP'ed into my server:
![image](https://user-images.githubusercontent.com/43744514/53103715-01fe8e80-3526-11e9-8d42-200e4681ea1f.png)

There are no webp versions of the images. So I thought - OK, maybe S3 Offload (#161) is intercepting the requests and passing them straight off to AWS. So I logged in and checked there for good measure:
![image](https://user-images.githubusercontent.com/43744514/53104161-c31d0880-3526-11e9-8566-8fe611ddb840.png)

Nothing there either 😭 Any ideas/recommendations/logs I can check?

**Comment by rosell-dk** [comment]
Hi!
 
It could be that the hocus-pocus I created to transfer the file path of the file to be converted to the script without passing it in query string isn’t working on your server setup. Transferring the file path in query string can give problems with firewalls, so I created .htaccess rules to transfer it in environment variables and request header instead. However, evidence is showing that it does not work on all servers. In that case, you should disable the “Do not pass source in Query String” option. It is only available in “Tweaked” mode (it is implicitly enabled in the other modes). It only has affect on the redirection to the converter (wod/webp-on-demand.php). I haven’t implemented transfer in query string for the “Convert non-existing webp-files upon request” feature (wod/webp-realizer.php), as it at the time seemed it wasn’t needed. I know that this is the option that you need. But you could try to check if the varied image responses mode works, and if disabling the option fixes it.

You could also try to edit wod/webp-realizer.php (which is the script, that are used for the “Convert non-existing webp-files upon request” feature) and uncomment some of the lines for debugging. First step could be to see if the redirection to that script works at all. In the top of webp-realizer, you could write:

```
echo 'hello'; exit;
```
Next, point your browser to an url of a non-existing webp (at the location it would exist, if it did).
You should see "hello" in the browser. If you don't it means that the redirection isn't working.

If the redirection works, next step could be to uncomment the line that says "//echo $destination; exit;".

**Comment by willstocks-tech** [comment]
It only just clicked in my head as well - so currently I reverse proxy apache via nginx. My stack is as follows:
- Ubuntu 18.04
- Apache 2.4.29 (`mod_disk_cache` disabled as it breaks my site!!! So no Apache level caching!)
- Nginx 1.14.0 (reverse proxy + caching)
- PHP 7.2.15 (FPM via Apache)
  - APCu (W3TC page caching)
- MySQL 5.7.25
- Redis 4.0.9
- HTTP/2 enabled

So I'm now wondering whether nginx is getting in the way some how and preventing this working!

I will add that echo now!

**Comment by willstocks-tech** [comment]
I can confirm that adding `echo 'hello; exit;` to the top of `/webp-express/wod/webp-realizer.php` does nothing. I cleared nginx's cache as well and restarted PHP, Apache and nginx for good measure

**Comment by rosell-dk** [comment]
Ok, time to look at the .htaccess rules, then. The plugin can either place the rules in root or in wp-content (it prefers the latter). Where are your rules placed? And can you paste the them here?

Perhaps Nginx are handling the request for the non-existing webp before it reaches Apache?

**Comment by willstocks-tech** [comment]
I've just changed to tweaked mode:
![image](https://user-images.githubusercontent.com/43744514/53154302-5f402180-35b2-11e9-89a6-f23b383535d4.png)

Now we're getting somewhere... but it's _not quite_ behaving as I expected:
![image](https://user-images.githubusercontent.com/43744514/53154423-ac23f800-35b2-11e9-9287-fe412109e968.png)

It's showing the .jpeg but with the `content-type` changed, despite in the config I've set "mingled" and "append .webp" (no .webp variant has been created in the same folder!)

**Comment by rosell-dk** [comment]
Set "Response on success" to "Original image" to avoid the "Varied image responses".

**Comment by rosell-dk** [comment]
Well, it seems that the redirection to wod/webp-on-demand.php is working.
But not the redirection to wod/webp-realizer.php

Perhaps there are other rules in the .htaccess file that takes control. Could you paste the .htaccess here?

**Comment by rosell-dk** [comment]
In webp-realizer.php, try inserting the following before the comment saying "// Last resort ...":

```php
    if ($allowInQS) {
        if (isset($_GET['xdestination'])) {
            return substr($_GET['xdestination'], 1);         // No url decoding needed as $_GET is already decoded
        } elseif (isset($_GET['destination'])) {
            return $_GET['destination'];     
        }
    }
```

**Comment by willstocks-tech** [comment]
> Set "Response on success" to "Original image" to avoid the "Varied image responses".

I have done this - still seeing `content-type: image/webp` 😞 Force updated .htaccess rules and restarted Apache and still the same.

> Could you paste the .htaccess here?

Root .htaccess or wp-content .htaccess?

> In `webp-realizer.php`, try inserting the following before the comment saying "// Last resort ...":

Done - not 100% sure what I should be seeing

**Comment by rosell-dk** [comment]
The .htaccess with WebP Express rules in it :)

**Comment by willstocks-tech** [comment]
Just checked - looks like that's /wp-content/.htaccess - the below is **all** that is in there. There's nothing else!

```

# BEGIN WebP Express
<IfModule mod_rewrite.c>
  RewriteEngine On

  # Redirect to existing converted image in same dir (if browser supports webp)
  RewriteCond %{HTTP_ACCEPT} image/webp
  RewriteCond %{DOCUMENT_ROOT}/wp-content/$1.$2.webp -f
  RewriteRule ^/?(.+)\.(jpe?g|png)$ $1.$2.webp [T=image/webp,E=EXISTING:1,L]

  # Redirect to existing converted image in cache-dir (if browser supports webp)
  RewriteCond %{HTTP_ACCEPT} image/webp
  RewriteCond %{REQUEST_FILENAME} -f
  RewriteCond %{DOCUMENT_ROOT}/wp-content/webp-express/webp-images/doc-root/wp-content/$1.$2.webp -f
  RewriteRule ^/?(.+)\.(jpe?g|png)$ /wp-content/webp-express/webp-images/doc-root/wp-content/$1.$2.webp [NC,T=image/webp,E=EXISTING:1,L]

  # Pass REQUEST_FILENAME to webp-realizer.php in request header
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{DOCUMENT_ROOT}/wp-content/$1 -f
  RewriteRule ^/?(.+)\.(webp)$ - [E=REQFN:%{REQUEST_FILENAME}]
  <IfModule mod_headers.c>
    RequestHeader set REQFN "%{REQFN}e" env=REQFN
  </IfModule>

  # WebP Realizer: Redirect non-existing webp images to webp-realizer.php, which will locate corresponding jpg/png, convert it, and deliver the webp (if possible) 
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{DOCUMENT_ROOT}/wp-content/$1 -f
  RewriteRule ^/?(.+)\.(webp)$ /wp-content/plugins/webp-express/wod/webp-realizer.php?xdestination=x%{SCRIPT_FILENAME}&wp-content=wp-content [NC,L]

  # Redirect images to webp-on-demand.php (regardless whether browser supports webp or not!)
  # - but only, when no existing converted image is found
  RewriteCond %{REQUEST_FILENAME} -f
  RewriteCond %{DOCUMENT_ROOT}/wp-content/$1.$2.webp !-f
  RewriteCond %{QUERY_STRING} (.*)
  RewriteRule ^/?(.+)\.(jpe?g|png)$ /wp-content/plugins/webp-express/wod/webp-on-demand.php?xsource=x%{SCRIPT_FILENAME}&wp-content=wp-content&%1 [NC,L]

  <IfModule mod_headers.c>
    <IfModule mod_setenvif.c>
      # Set Vary:Accept header for the image types handled by WebP Express.
      # The purpose is to make CDN aware that the response varies with the Accept header, so it should not just use the URL as cache key, but also the Accept header. 
      SetEnvIf Request_URI "\.(jpe?g|png)" ADDVARY
      Header append "Vary" "Accept" env=ADDVARY

      # Set X-WebP-Express header for diagnose purposes
      # Apache appends "REDIRECT_" in front of the environment variables defined in mod_rewrite, but LiteSpeed does not.
      # So, the next line is for Apache, in order to set environment variables without "REDIRECT_"
      SetEnvIf REDIRECT_EXISTING 1 EXISTING=1
      Header set "X-WebP-Express" "Redirected directly to existing webp" env=EXISTING
    </IfModule>
  </IfModule>

</IfModule>
<IfModule mod_mime.c>
  AddType image/webp .webp
</IfModule>

# END WebP Express
```

**Comment by rosell-dk** [comment]
You must also disable the "Redirect directly to converted image when available" option. This is the option that is responsible for the direct redirects

**Comment by willstocks-tech** [comment]
OK - I'm now back to `content-type: image/jpeg` - I've just checked the same folder via FTP and no .webp's exist yet

**Comment by rosell-dk** [comment]
The new lines in `webp-realizer.php` makes webp-realizer.php accept when filename is passed in query string (xdestination=...).

**Comment by rosell-dk** [comment]
But the "Redirect directly to converted image when available" functionality successfully found an existing webp to redirect to. So there must be at least one webp!

**Comment by willstocks-tech** [comment]
![image](https://user-images.githubusercontent.com/43744514/53157468-7c2c2300-35b9-11e9-8c50-314380e5e140.png)
There's absolutely nothing in the folder (which I'm still looking at: https://willstocks.co.uk/wp-content/uploads/2018/10/Cheerson-CX10-Review.jpg) - is it possible that it's not "saving" the webp for some reason, it's just "on-the-fly" webp-ing it?

**Comment by rosell-dk** [comment]
Requesting the following image gives access denied:
https://cdn.willstocks.com/wp-content/uploads/2018/10/Cheerson-CX10-Review-100x100.jpg.webp

**Comment by rosell-dk** [comment]
The "X-WebP-Express" header is only set in the .htaccess, and only when an existing webp was found and redirected to.

**Comment by rosell-dk** [comment]
mysterious!

**Comment by rosell-dk** [comment]
You are in 2019/02 folder. You should look in 2018/10 folder

**Comment by rosell-dk** [comment]
I think we should persue why a request to an existing webp results in Access denied.
Perhaps you need to add webp mime type in Apache or Nginx.

**Comment by rosell-dk** [comment]
In Nginx, try to locate a configuration file called "mime.types". Add the following: `image/webp  webp;` if it isn't there.

**Comment by rosell-dk** [comment]
Have you enabled mod_mime in Apache?
If not, then the "AddType image/webp .webp" in the .htaccess will not take effect.
Or you can perhaps try to add "image/webp webp" to `/etc/mime.types` (https://askubuntu.com/questions/258780/how-to-add-mime-type-for-the-apache-webserver)

**Comment by willstocks-tech** [comment]
> Requesting the following image gives access denied:
> https://cdn.willstocks.com/wp-content/uploads/2018/10/Cheerson-CX10-Review-100x100.jpg.webp

See #161 - I'm using S3 Offload to offload assets to AWS S3 and Cloudfront. I can setup a W3TC rule to upload .webp files when they're created by WebP Express - however I don't think WebP will handle the rewrites correctly for these files as they're not "locally" served.

You can instead find the file here as the webp has been generated on my server: https://willstocks.co.uk/wp-content/uploads/2018/10/Cheerson-CX10-Review.jpg.webp



> You are in 2019/02 folder. You should look in 2018/10 folder

Ahhhhhhh - my bad!!!! Haven't had a cup of tea yet!

> I think we should persue why a request to an existing webp results in Access denied.
> Perhaps you need to add webp mime type in Apache or Nginx

Already setup webp in Apache and Nginx - I think my next issue to work out is the S3/Cloudfront bit

**Comment by willstocks-tech** [comment]
So that's good news! The webp files are being generated!!! Now I just need to work out how to:
1) Upload them to S3 (which I think I can do via a W3TC Customer Files upload rule) when they're created
2) Make sure that I rewrite image requests to the webp if they exist (I'm banking on an "if webp exists, rewrite CDN url to append .webp")

**Comment by rosell-dk** [comment]
I need to attend to a customer. I'll be back. Probably not today.

**Comment by willstocks-tech** [comment]
Thanks for all your help @rosell-dk 😁

**Comment by willstocks-tech** [comment]
OK, so images do seem to convert (as long as I call them directly) - now I just need to figure out how to get around my "domain-sharding" issue, where I'm uploading the images directly to AWS S3 and then serving them from there (via CloudFront).

There are two issues with this:

1. When WebP Express converts the images to .webp, S3 Offload doesn't trigger and upload them to AWS (I potentially can work around this... there might be a way for me to hook into S3 Offload once WebP Express has generated and stored the WebP image)
2. Rewriting the URL's... so at the moment they serve from https://cdn.willstocks.com, _NOT_ my primary site domain (https://willstocks.co.uk) and I haven't done anything relating to `WP_CONTENT_URL` because it's all handled via S3 Offload. I'm not sure what would happen if I changed the URL, as it's not only the uploads that would be affected, it would be everything? And I don't serve _everything_ in `wp-content` from my CDN. Therefore, I'm wondering if there's a way that I can:
    i. check for images on `*.willstocks.com/_file path_.jpg`
    ii. check whether a webp exists at the same `_file path_.jpg` locally
    iii. If it does, change the output url file path to `.webp` rather than `.jpeg` or `.png`

I think this is more appropriately discussed in: #161 though!
