### ISSUE TITLE
Images not converting, throws PHP error

### ISSUE THREAD

**Issue by devoutpost** [rosell-dk/webp-express#208]
Though on the main settings page it shows that EWWW image converter is working, upon saving settings the test image is converted, but viewing the debug shows the following errors:

Warning: Invalid argument supplied for foreach() in /public_html/wp-content/plugins/webp-express/vendor/rosell-dk/webp-convert/build/webp-on-demand-2.inc on line 214
Conversion failed. None of the tried converters are operational
Conversion failed. None of the tried converters are operational

And though the folders are created for the webp images, and the links to those images within the new created folder are added to the webpage, no images (not even backup images) show up, and no images exist in those folders.

Would appreciate some fix or a pointing in the right direction.

**Comment by rosell-dk** [comment]
The offending line says"
```php
foreach ($options['converters'] as $converter) {
```

So it seems the converters option is null.
But you see the converters on the options page, right?
First, try saving the options. This will recreate the two options files.

If that does not work, try opening /wp-content/webp-express/config/config.json.
This is where the options for WebP express is stored.
Now check if the converters are there.

You should see something like this:
```json
    "converters": [
        {
            "converter": "gd",
            "options": {
                "skip-pngs": true
            },
            "working": true
        },
        ...
```

If this looks ok, next inspect the `wod-options.json` file.
This contains options for the converter script. Many of the settings are the same as in config.json.
Again, look for the "converters" section, and tell me what you got

**Comment by rosell-dk** [comment]
@devoutpost : are you there?
