### ISSUE TITLE
Blank settings page

### ISSUE THREAD

**Issue by bellinitia** [rosell-dk/webp-express#210]
Hi! I am experiencing a bug, I read something similar around but it's not the same thing... If I click on what should be the settings page, it shows just a completely blank page. With a 404-to-home auto redirection plugin enabled, it redirects to home instead of showing the blank page (that’s why I am saying it's a similar problem).
Any idea?
Thanks!

Ps: I already tried to disable all other plugins to be sure it was not a conflict with something, but with no results.

**Comment by rosell-dk** [comment]
Yes, I get such reports on a regular basis. But I have not been able to track it down. Perhaps we can do it with your help... Can you try to enable debugging and perhaps also debug log, and see what shows up?
Here is a guide: https://codex.wordpress.org/Debugging_in_WordPress

Thanks, Bjørn

**Comment by bellinitia** [comment]
Yep, I'll try today and I'll let you know asap.

**Comment by rosell-dk** [comment]
thanks :)

**Comment by bellinitia** [comment]
So I did some tests, it seems to work with a local copy of my website, but not in the live one. Unfortunately, I do not have access to the server itself of the live version, so I could not enable the debug mode (I tried with a plugin but it broke everything, probably due to some server-side security system). I guess it could be due to some settings of the hosting platform or something?

**Comment by Spence1115** [comment]
I'm having the same issue, runs locally, not on our server (Kubernetes)
 
Logs:
`[Wed May 15 15:03:35.773362 2019] [php7:warn] [pid 20] [client 100.98.0.48:41632] PHP Warning:  include_once(/var/www/html/wp-content/plugins/webp-express/lib/classes/../../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/webp-express/lib/classes/TestRun.php on line 10, referer: https://ourdomain/wp-admin/plugins.php?plugin_status=all&paged=1&s`

`[Wed May 15 15:03:35.773401 2019] [php7:warn] [pid 20] [client 100.98.0.48:41632] PHP Warning:  include_once(): Failed opening '/var/www/html/wp-content/plugins/webp-express/lib/classes/../../vendor/autoload.php' for inclusion (include_path='.:/usr/local/lib/php') in /var/www/html/wp-content/plugins/webp-express/lib/classes/TestRun.php on line 10, referer: https://ourdomain/wp-admin/plugins.php?plugin_status=all&paged=1&s`

`[Wed May 15 15:03:35.773462 2019] [php7:error] [pid 20] [client 100.98.0.48:41632] PHP Fatal error:  Uncaught Error: Class 'WebPConvert\\Converters\\ConverterHelper' not found in /var/www/html/wp-content/plugins/webp-express/lib/classes/TestRun.php:99\nStack trace:\n#0 /var/www/html/wp-content/plugins/webp-express/lib/classes/Config.php(53): WebPExpress\\TestRun::isLocalQualityDetectionWorking()\n#1 /var/www/html/wp-content/plugins/webp-express/lib/classes/Config.php(168): WebPExpress\\Config::getDefaultConfig(false)\n#2 /var/www/html/wp-content/plugins/webp-express/lib/classes/Config.php(280): WebPExpress\\Config::fix(false, true)\n#3 `

**Comment by rosell-dk** [comment]
@Spence1115: Thanks for providing error message!

The message basically says that the following file does not exist:
`/var/www/html/wp-content/plugins/webp-express/lib/classes/../../vendor/autoload.php`

- which should be the same as saying that the following file does not exist:
`/var/www/html/wp-content/plugins/webp-express/vendor/autoload.php`

Can you please check if you have this file at that location?

**Comment by rosell-dk** [comment]
If you *do* have that file at that location, it would seem that the double dots poses a problem.
In that case, try this:
1. Open `/var/www/html/wp-content/plugins/webp-express/lib/classes/TestRun.php` in a editor.
2. In line 10, you should see this:

`include_once __DIR__ . '/../../../vendor/autoload.php';`

remove that and replace with this instead:

`include_once WEBPEXPRESS_PLUGIN_DIR . '/vendor/autoload.php';`

Does that help?

**Comment by Spence1115** [comment]
I'll give it a try and let you know.

**Comment by rosell-dk** [comment]
Any news?
btw, if you see no "vendor" folder in the plugin dir, it might has something to do with [this issue](https://wordpress.org/support/topic/gitignore/#post-11537220)

**Comment by Spence1115** [comment]
Yeah it was the 'vendor' on gitignore issue. Removing that from gitignore fixed it.

**Comment by rosell-dk** [comment]
Will it suffice if I remove the .gitignore file from the plugin on Wordpress (but keep it in github)?

**Comment by Spence1115** [comment]
Should do, yeah 👍

**Comment by rosell-dk** [comment]
Done - just released 0.13.2 on wordpress

**Comment by rosell-dk** [comment]
The fix unfortunately does [not fix the issue for everybody](https://wordpress.org/support/topic/404-error-from-settings-page/#post-11540409).

**Comment by rosell-dk** [comment]
I discovered and fixed a bug that would lead to blank settings page. Hopefully the issue is fixed for all now

**Comment by bellinitia** [comment]
> I discovered and fixed a bug that would lead to blank settings page. Hopefully the issue is fixed for all now

I'm sorry about it, but I still have the same problem :/

**Comment by rosell-dk** [comment]
@bellinitia: Sorry, by fixed, I mean fixed here on the master branch in github. It has not been released yet. I expect it to be released in three days time or so

**Comment by bellinitia** [comment]
> @bellinitia: Sorry, by fixed, I mean fixed here on the master branch in github. It has not been released yet. I expect it to be released in three days time or so

Oh, sorry! My bad, didn't get it. Thank you! :)
