### ISSUE TITLE
media upload time

### ISSUE THREAD

**Issue by jedidiah13** [rosell-dk/webp-express#216]
when i updated the plugin from 0.12 to 0.13 our media upload times for photos seemed to triple.  is this a known issue? normal?  others experiencing?  we are normally dealing with pictures no larger than 1024 x 720 pixels or smaller

**Comment by rosell-dk** [comment]
It is probably because upload now triggers a conversion of both the uploaded image and all its thumbnails.
You can disable that functionality if you wish (below the conversion methods, there is a new option in 0.13.0)
