### ISSUE TITLE
"The response is not a valid JSON response" response when uploading an image

### ISSUE THREAD

**Issue by rosell-dk** [rosell-dk/webp-express#228]
Even with Alter HTML disabled...
More details here: https://wordpress.org/support/topic/updating-failed-when-updating-a-page-or-post/#post-11422396

**Comment by andreiglingeanu** [comment]
Can confirm this happens. I imagine it somehow breaks out the nested JSON escaping and makes unparseable by `JSON.parse()`.

Try this:

1. See how Chrome is able to parse the JSON properly: https://cl.ly/3e05550ba2c3
2. Now, I will take the same JSON string through [this](https://jsonlint.com/) tool: https://cl.ly/221954f2dcf2
3. If I try to parse this formatted string with Firefox `JSON.parse()`, it gives a bit more useful information: https://cl.ly/292457233dc1. Here's the full JSON string, for reference: https://gist.github.com/andreiglingeanu/20957c86f1f8e4bc6c9db99237995dba

This is definitely a very strange behavior and I believe is due to the plugin's after html logic. Maybe you have some logic that runs even when this option is disabled?

**Comment by rosell-dk** [comment]
Interesting - the one that originally had this problem [did not](https://wordpress.org/support/topic/updating-failed-when-updating-a-page-or-post/#post-11422396) have html altering enabled. - But I did suspect that HTML altering might be the cause of the problem. Although I did take steps to prevent it, it might be the case that the JSON is altered

**Comment by rosell-dk** [comment]
I shall be very glad for help solving this.
I suspect that what we need is a line preventing HTML altering for JSON.
It shall go into the file `wp-content/plugins/webp-express/lib/AlterHtmlInit.php`, in the method `alterHtml`, around line 27.

**Comment by rosell-dk** [comment]
It might be that it only happens for output buffering or the other hooks. What is your "Alter HTML > Where to replace" option set to now?

**Comment by andreiglingeanu** [comment]
Yep. I just re-checked again. It indeed does not happen when html altering is not enabled.

The easiest way to reproduce (my case at least):

1. Empty WordPress with Gutenberg
2. Install plugin & activate html altering, specifically `Replace image URLs` option, not the one that does `<img />` -> `<picture />`
3. Add a post and insert a separator with a style other than default (this adds some JSON inside the post content): https://cl.ly/4e68df361525
4. Click Update and watch it fail.


Key point: the problem reproduces with `Replace image URLs` option enabled.

**Comment by andreiglingeanu** [comment]
It seems to me that `simple_html_dom` class is the one responsible for this behavior.

If I do an early return inside the `replaceHtml` method from `dom-util-for-webp/src/ImageUrlReplacer.php`, it works just fine. Of course the actual replace won't perform :)

```php
    public function replaceHtml($html) {
        if ($html == '') {
            return '';
        }

        // there's the early return
		return $html;

		// ...
		// the rest of the logic
	}
```

**Comment by andreiglingeanu** [comment]
Indeed, `dom-util-for-webp/src/PictureTags.php` uses `str_get_html()` parser only for image attributes, while `dom-util-for-webp/src/ImageUrlReplacer.php` parses the whole document and then does the replacing. I suspect that by altering the logic of `ImageUrlReplacer` to make it more narrowed (without parsing the whole document) -- it'll be a bit safer.

And by the way, is there a problem with straight URL matching and replacing with regex, without even looking at the context of the URL?

**Comment by rosell-dk** [comment]
Yes, there are potential problems luring with straight up URL matching. For example, there might be URLs in javascript, which might break. Also we do not want `<source srcset="1.png" type="image/png">` to become `<source srcset="1.png.webp" type="image/png">` - the type should then be changed. 

But if `simple_html_dom` is responsible for this, then it seems that regex is a better solution. `simple_html_dom` is responsible for other problems too - problems have been reported regarding attributes containing special characters. 

The "problems" with a regex solution seems to be merely challenges. I actually went for regex to begin with, but changed cause because of challenges and that using `simple_html_dom` produced much cleaner code. But I can change back to the original cause :). I even considered allowing users to choose between the two methods.

https://regexr.com/46isf
https://github.com/rosell-dk/dom-util-for-webp

**Comment by rosell-dk** [comment]
Thanks for the reproduction steps, btw. I can reproduce :)

**Comment by rosell-dk** [comment]
WebP Express in fact *does* run HTML altering on the JSON.
And we have that

`{"content":{"raw":"<hr class=\"wp-block-separator is-style-dots\"\/>...` becomes:
`{"content":{"raw":"<hr class=\"wp-block-separator is-style-dots\"\>...`

Not using `simple_html_dom` might help. But a question posses itself: Should the plugin touch urls in JSON? While this may sometimes be beneficial, I suspect that it could also lead to trouble.

**Comment by rosell-dk** [comment]
For those looking for a solution before this is fixed:

The problem does *not* occour when "Use content filtering hooks (the_content, the_excerpt, etc)" is selected in *Alter HTML > Where to replace*. So simply change that option

**Comment by rosell-dk** [comment]
For some reason `wp_doing_ajax` is not true in this case. And I cannot use $_SERVER['HTTP_X_REQUESTED_WITH'] either, as suggested [here](https://stackoverflow.com/questions/14348470/is-ajax-in-wordpress)

So the solution seems to simply check if it is JSON.

Here is one way to do it:
```php
        // Do not alter JSON
        // https://stackoverflow.com/questions/6041741/fastest-way-to-check-if-a-string-is-json-in-php
        json_decode($content);
        if (json_last_error() == JSON_ERROR_NONE) {
            return $content;
        }
```

But decoding the JSON is uneccessary. Instead, we could examine the first couple of characters.
https://stackoverflow.com/questions/6041741/fastest-way-to-check-if-a-string-is-json-in-php
https://stackoverflow.com/questions/2583472/regex-to-validate-json/3845829#3845829

**Comment by andreiglingeanu** [comment]
Personally, I'd try first to use a different HTML parser before rushing into straight into a regex solution.

What I've came up with in another project was this: 

```php
$parser = new Parser();

$output = $parser->add_attribute_to_images(
  $html,
  'sizes',
  'attribute_value'
);

$output = $parser->remove_attribute_from_images(
  $html,
  'sizes',
);

$output = $parser->rename_attribute_from_images(
  $html,
  'sizes',
  'lazy-sizes'
);
```

[Parser source.](https://gist.github.com/andreiglingeanu/8e3afa19cfb2394bc21e502bed12e47c) It's a very simple regex based solution that worked **really** well for me. It has three actions: `add_attribute`, `remove_attribute`, `rename_attribute`. I was able to safely pass a HTML blog to it and it'll happily do its thing without leaving anything extra along the way. It might need some adjustments for HTML in JSON (it contains some escape characters).

I'd go with a proper parser especially for your issue with `type="image/png"` -- it needs proper contextual treatment.

**Comment by rosell-dk** [comment]
I guess rather than detecting if it looks like JSON, we should detect if it looks like HTML. It is presumably also easier. As easy as in:

```php
        // Exit if it doesn't look like HTML (and thus prevent altering JSON)
        if (!preg_match('#\\s<*#')) {
            return $content;
        }
```

**Comment by andreiglingeanu** [comment]
After testing it, this condition does not behave well for me:

```php
        // Exit if it doesn't look like HTML.        
        if (!preg_match('#\\s<*#', $content)) {
            return $content;
        }

```

But this one does work as expected :)

```php
        // Do not alter JSON
        // https://stackoverflow.com/questions/6041741/fastest-way-to-check-if-a-string-is-json-in-php
        json_decode($content);
        if (json_last_error() == JSON_ERROR_NONE) {
            return $content;
        }
```

**Comment by rosell-dk** [comment]
Ok, I was too quick with the regex. I have corrected it above.

And thank YOU for helping out nailing this bug! It may actually affect many people who will not know what hit them and where to report. So you can pad yourself on the shoulders!

**Comment by andreiglingeanu** [comment]
Sure! I'm glad we got it ruled out so fast.

**Comment by rosell-dk** [comment]
I plan to release first thing in the morning. Cheers!
