### ISSUE TITLE
Fatal Error on when used in combination with Shortpixel  - Enable Media Replace

### ISSUE THREAD

**Issue by portalzine** [rosell-dk/webp-express#236]
Getting a Fatal Error,  when used in combination with the Shortpixel Enable Media Replace.
https://de.wordpress.org/plugins/enable-media-replace/

PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function WebPExpress\HandleUploadHooks::handleUpload(), 1 passed in ../wp-includes/class-wp-hook.php on line 286 and at least 2 expected in .../wp-content/plugins/webp-express/lib/classes/HandleUploadHooks.php:59
Stack trace:
#0 .../wp-includes/class-wp-hook.php(286): WebPExpress\HandleUploadHooks::handleUpload(Array)
#1 .../wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 .../wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 .../wp-content/plugins/enable-media-replace/upload.php(274): do_action('wp_handle_uploa...', Array)
#4 .../wp-content/plugins/enable-media-replace/enable-media-replace.php(113): require_once('/usr/www/users/...')
#5 .../wp-includes/class-wp-hook.php(286): emr_options('')
#6.../wp-content/plugins/webp-express/lib/classes/HandleUploadHooks.php on line 59

Alex

**Comment by kolli1337** [comment]
I'm also getting this error when trying to replace an image via the plugin mentioned by @portalzine 

Plugin versions are:

WebP Express: 0.13.1
Enable Media Replace: 3.2.9

When I deactivate WebP Express, replacing the image works fine.

**Comment by rosell-dk** [comment]
Try changing line 59 in 'wp-content/plugins/webp-express/lib/classes/HandleUploadHooks.php':

from:
`public static function handleUpload($filearray, $overrides, $ignore = false)`

to:
`public static function handleUpload($filearray, $overrides = false, $ignore = false)`

**Comment by kolli1337** [comment]
Yes, this fixed the error for me 👍
