### ISSUE TITLE
Better processing feedback

### ISSUE THREAD

**Issue by KevinBatdorf** [rosell-dk/webp-express#247]
Once the bulk processing starts, for example, the feedback is lost. If you have thousands of images processing, then keeping up is near impossible. I think the files should be prepended to the top, and maybe add an overall status fixed outside (ex. something like `processing image 370/27349 (1% complete)`).

<img width="1048" alt="Screen Shot 2019-05-26 at 9 18 57 PM" src="https://user-images.githubusercontent.com/1478421/58383067-4e150f80-7ffc-11e9-851b-b01849b75e3a.png">

**Comment by rosell-dk** [comment]
yeah, that would be an improvement. As bulk conversion is rarely needed, it is however not on top of the priorities. Also, I have plans to make an interface where you can both convert a single file, or bulk convert folder, and you can play around with the conversion settings, and also compare the results visually

**Comment by KevinBatdorf** [comment]
Ok sounds good. No need to keep this issue open then. Thanks
