### ISSUE TITLE
Version 0.14.4 throws error "Class 'WebPExpress\\Paths"

### ISSUE THREAD

**Issue by chrillek** [rosell-dk/webp-express#281]
My apache log shows this error message:
`AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'WebPExpress\\Paths' not found in /var/www/wordpress/wp-content/plugins/webp-express/lib/classes/ConvertHelperIndependent.php:210\nStack trace:\n#0 /var/www/wordpress/wp-content/plugins/webp-express/lib/classes/ConvertHelperIndependent.php(233): WebPExpress\\ConvertHelperIndependent::createLogDir('/var/www/wordpr...')\n#1 /var/www/wordpress/wp-content/plugins/webp-express/lib/classes/ConvertHelperIndependent.php(306): WebPExpress\\ConvertHelperIndependent::saveLog('/var/www/wordpr...', '/var/www/wordpr...', '*WebP Convert 2...', 'Conversion trig...')\n#2 /var/www/wordpress/wp-content/plugins/webp-express/wod/webp-on-demand.php(226): WebPExpress\\ConvertHelperIndependent::serveConverted('/var/www/wordpr...', '/var/www/wordpr...', Array, '/var/www/wordpr...', 'Conversion trig...')\n#3 {main}\n  thrown in /var/www/wordpress/wp-content/plugins/webp-express/lib/classes/ConvertHelperIndependent.php on line 210\n', referer: https://bru6.de/unterwegs/religionskitsch-der-orthodoxen/
`
apparently when trying to convert a jpeg image to webp for the first time.

**Comment by rosell-dk** [comment]
I see, understand, and shall fix
