### ISSUE TITLE
plugin discontinued?

### ISSUE THREAD

**Issue by bobhuf** [rosell-dk/webp-express#282]
> This plugin was closed on June 20, 2019 and is no longer available for download.

Sad to see you go. What happened?

**Comment by rosell-dk** [comment]
It has been closed for download temporarily because they found a security issue.

The issue is not too serious as you had to have access to the WebP Express settings in order to do misdeeds. But well, closed it, they did.

**Comment by bobhuf** [comment]
Oh, well I'm glad to hear it's not permanent.
