### ISSUE TITLE
Why was this removed from the WP Plugin Repo?

### ISSUE THREAD

**Issue by matgargano** [rosell-dk/webp-express#285]
https://wordpress.org/plugins/webp-express/

**Comment by rosell-dk** [comment]
Working to get it back on!
See 
https://wordpress.org/support/topic/this-plugin-was-closed-on-june-20-2019-and-is-no-longer-available-for-download/

**Comment by cyberxsboy** [comment]
> Working to get it back on!
> See
> https://wordpress.org/support/topic/this-plugin-was-closed-on-june-20-2019-and-is-no-longer-available-for-download/

How long do you expect to see the latest version of your optimization in Wordpress. org's plug-in library?
