### ISSUE TITLE
Relax abs path sanity check for Windows

### ISSUE THREAD

**Issue by rosell-dk** [rosell-dk/webp-express#293]

**Comment by lwxbr** [comment]
Something I can help? What you think we use a lib in composer that works both for linux, windows and mac osx?

**Comment by rosell-dk** [comment]
That could very well be a good idea. 
As I'm going for vacation in a few days, I will however just make a very quick fix.

As I have learned to take sanitize checks very serious, I will only allow Windows type paths on Windows.

Do you think detection covers all Windows machines?

```
if (strpos(strtolower($_SERVER['SERVER_SOFTWARE']), 'microsoft') !== false) {
...
}
```

**Comment by rosell-dk** [comment]
WINNT seems to be possible too

**Comment by lwxbr** [comment]
My friend, look at this beauty lib: https://packagist.org/packages/webmozart/path-util. I think that will solve all our problems with path resolution. It's awful deal with "PATH . FILE" thing. I will test in Windows. When I got some time I send you a pull request.

**Comment by rosell-dk** [comment]
It looks promising. Again, I only have a few hours of computer time before vacation and I shall go with a simple hack for now

**Comment by lwxbr** [comment]
@rosell-dk , I found that lib, hope it helps: https://packagist.org/packages/tivie/php-os-detector

**Comment by rosell-dk** [comment]
Thanks, that lib looks nice and easy (don't like its not tested with php 5.5 though - but they claim it should work on 5.5)

**Comment by rosell-dk** [comment]
Only thing is that I sanity check paths all over in the Wordpress plugin, but only load the composer autoload a few places. I dare not add autoloading all over with this little time to test.

**Comment by rosell-dk** [comment]
But the lib is very few lines. I'll examine and grab!

**Comment by rosell-dk** [comment]
Here is what I need:
`
          case "WINDOWS":
            case "WINNT":
            case "WIN32":
            case "INTERIX":
            case "UWIN":
            case "UWIN-W7":
                $family  = WINDOWS_FAMILY;
                $osConst = WINDOWS;
                break;
`

**Comment by lwxbr** [comment]
Why you do not want use the lib? It is heavy? Or is just a quick fix?

**Comment by rosell-dk** [comment]
I don't include vendor/autoload.php on all wordpress pages.
