### ISSUE TITLE
Getting a 403 for some images

### ISSUE THREAD

**Issue by GiacomoLaw** [rosell-dk/webp-express#301]
Site: https://www.thenerdystudent.com/

Getting 403s from some images. I use BunnyCDN and have Browser WEBP Support. I am also using Wordfence and Cloudflare. I have Wordfence code execution protection in place in the uploads directory.

I've had to remove the plugin. 

Thanks

**Comment by rosell-dk** [comment]
From #303#issuecomment-517439245 I conclude that this was fixed with #303. Although I don't understand how that could fix it...
