### ISSUE TITLE
Changing exitWithError to public?

### ISSUE THREAD

**Issue by GiacomoLaw** [rosell-dk/webp-express#303]
https://github.com/rosell-dk/webp-express/blob/23d8ee5258032660eefbc61a16159bb0fff9f2e9/wod/webp-realizer.php#L18-L22

Would changing it to `public` be a security risk? I had to do so to fix issues with my host.

Thanks

**Comment by rosell-dk** [comment]
No, it will not pose a security risk to change it to `public`.

I'm however curious to hear about what kind of hosting issues this fixes?

But well, I now see that I actually call `WebPRealizer::exitWithError` from within that same file (when the php is accessed directly) - and this fails unless `exitWithError` is public. I shall make it public...

**Comment by rosell-dk** [comment]
@GiacomoLaw: I’d like to credit you in the release notes for reporting this. I'm routinely crediting people who reported a problem, which caused a fix. The purpose of this is showing that I appreciate feedback and this way encourage others to report any problem that they might encounter. 

When doing this, I usually write the country the person is from. So: Are you ok with being credited, and may I inquire where you are from?

Thanks,
Bjørn (Denmark)  ;)

**Comment by GiacomoLaw** [comment]
That would be great, thanks! I’m from the U.K.  

Apologies for the late reply - I’ve had limited connection. My issue was that images were returning as 403s, but changing it to `public` fixed that. 

Thanks for the great plugin!

**Comment by rosell-dk** [comment]
The fix has just been released (0.14.22)
