### ISSUE TITLE
Do not rely on DocumentRoot

### ISSUE THREAD

**Issue by rosell-dk** [rosell-dk/webp-express#322]
`$_SERVER["DOCUMENT_ROOT"]` is unreliable and might have been set up wrong.

Also, doing `realpath($_SERVER["DOCUMENT_ROOT"])` can result in an open_basedir restriction.

**Comment by rosell-dk** [comment]
https://wordpress.org/support/topic/sanitation-check-failed-for-destination-path-does-not-exist/#post-11837923

**Comment by rosell-dk** [comment]
Hm, I'm not sure it will be possible to do entirely without document root.
I'm having trouble coming up with redirection rules that doesn't rely on document root.
The following is an excerpt of rules for redirecting to existing converted image where the location has set to "separate", and both the upload folder and the wp-content folder has been moved.

```
# Redirect to existing converted image in cache-dir (if browser supports webp)
  RewriteCond %{HTTP_ACCEPT} image/webp
  RewriteCond %{REQUEST_FILENAME} -f
  RewriteCond %{DOCUMENT_ROOT}/wp-content-moved/webp-express/webp-images/doc-root/wordpress/uploads-moved/$1.$2.webp -f
  RewriteRule ^/?(.+)\.(jpe?g|png)$ /wp-content-moved/webp-express/webp-images/doc-root/wordpress/uploads-moved/$1.$2.webp [NC,T=image/webp,E=EXISTING:1,L]
```

**Comment by rosell-dk** [comment]
Ah, the above is not a problem.
I can simply print the absolute path.
This however is not so stable, as it will not survive if website is moved.
To fix that, I can check if the absolute path starts with $_SERVER['DOCUMENT_ROOT']. If it does, then replace the beginning of the path with "%{DOCUMENT_ROOT}"

I can of course could of course

**Comment by cantoute** [comment]
> I can simply print the absolute path.
I wouldn't do this...

perhaps use env vars that if set takes over ?

SetEnvIf THE_DOC_ROOT  .  THE_DOC_ROOT=%{DOCUMENT_ROOT}
and
RewriteCond %{ENV:THE_DOC_ROOT} ...

but a better one, is to have DOCUMENT_ROOT properly set... lots of things can bug in wordpress if this isn't right.

Thanks for your gr8 work.

As it is, your plugin works really nicely.

**Comment by rosell-dk** [comment]
The current rules rules requires calculation of the relational path between document root and the plugins folder. This is impossible on the systems where document root is not set correctly or is outside open_basedir restriction. 
It is only on these few systems that I need to change the rules. If document root is available, the current rules will be generated (I have a few adjustments, but I'm going to use more or less the same rules as now for systems with document root available)

**Comment by rosell-dk** [comment]
017e6be

**Comment by rosell-dk** [comment]
The "cache" dir is "wp-content/webp-express/webp-images" (unless wp-content has been moved).
Before the latest commit, it contained one folder: "doc-root" (and a folder for the web service, if that is activated). Now - if it is detected that document root cannot be used - it will also contain a "uploads" folder. The internal structure of that folder will mirror the structure of the uploads folder. And a "themes" folder, etc.
It is possible to select that new structure if one wish by editing the config and changing "destination-structure" from "doc-root" to "image-roots". It will soon be part of the UI. I however need to make automatic relocation of existing webps first

**Comment by rosell-dk** [comment]
Fixed
