### ISSUE TITLE
PHP Fatal error:  Call to undefined function WebPExpress\wp_get_image_mime()

### ISSUE THREAD

**Issue by Aterbonus** [rosell-dk/webp-express#327]
The plugin info page tells us that the supported WordPress versions are 4.0 and up, but [wp_get_image_mime was introduced in WordPress 4.7.1](https://developer.wordpress.org/reference/functions/wp_get_image_mime/#changelog).

The problem is in [this line](https://github.com/rosell-dk/webp-express/blob/3886d922f17fe1e54038a0af666e33261ca80648/lib/classes/Mime.php#L14)

**Comment by rosell-dk** [comment]
thanks. Fixed
