### ISSUE TITLE
Failed opening required  ... webp-express/lib/classes/Exception.php'

### ISSUE THREAD

**Issue by NotARobit** [rosell-dk/webp-express#353]
"new Exception" is being caught by the autoloader.

https://github.com/rosell-dk/webp-express/blob/152af30be15a4ec8c95ce445bc74d77cda717174/lib/classes/Convert.php#L47

**Comment by rosell-dk** [comment]
thanks

**Comment by rosell-dk** [comment]
released in 0.16.0
