### ISSUE TITLE
Fail to get webp express cloud service to run

### ISSUE THREAD

**Issue by cngi1** [rosell-dk/webp-express#360]
1. Setup and Local test all work. Local test of 4 test images using cwebp success.
2. Setup of service endpoint.
https://images.domain.org/webp-express-web-service
3. Requesting webp express site only gets 404 errors. This cloud service site fresh install only has 1 plug-in, webp express installed. Sample page is displayed.

No errors in server logs. 404 in test results on requesting site.

Only changes made would be done by webp express.

Suggestions?

**Comment by cngi1** [comment]
Result: Failure
Message: WPC was not found at the specified URL - we got a 404 response.

**Comment by rosell-dk** [comment]
Can you give me the real URL of the service? You can email it to me at it@rosell.dk

**Comment by rosell-dk** [comment]
Oh, if you get a 404 there is not much point in emailing me the URL

**Comment by rosell-dk** [comment]
But can you instead email me credentials to the Wordpress you set up for doing the service?

**Comment by rosell-dk** [comment]
Weekend...

**Comment by cngi1** [comment]
This started working after resetting and setting pretty permalinks. Not a plugin just the normal permalinks menu.  Stopped the 404 errors.  A search on the web suggested 404 errors because of permalinks for rest services.  

The requesting site fails all redirection tests for a web page image but passes the conversion method tests. So webp service seems to be working. closing this thread.
