### ISSUE TITLE
Fontawesome Icons not showing?

### ISSUE THREAD

**Issue by jockebq** [rosell-dk/webp-express#377]
Using this great plugin on my nginx server with the recommended configuration. Everything works great except the lazy loaded fontawesome icons. They are externally loaded and used by my theme TheGem.

What could be wrong? I have confirmed that all other images are working

**Comment by rosell-dk** [comment]
If you give me the URL of your website, I can have a look. You can email it to me if you prefer not to share (it@rosell.dk). I see that [TheGem](https://themeforest.net/item/thegem-creative-multipurpose-highperformance-wordpress-theme/16061685) requires a purchase.

**Comment by jockebq** [comment]
Sorry about this @rosell-dk , I actually installed Fast Velocity Minify just before this, and that was the one causing the issue. You can close this, as this is not relevant to webp-express.

Thanks for a great plugin!

**Comment by rosell-dk** [comment]
ok, glad you found the cause!
