### ISSUE TITLE
Cannot convert images that contains non ascii letters.

### ISSUE THREAD

**Issue by Lars-Hagen** [rosell-dk/webp-express#386]
If you want to convert an image where the path contains a non ASCII character, it strips it.

Animalø.png becomes Animal.png

This is because escapehellarg strips it, you will have to set the locale to en_US.UTF-8, or just any locale with utf8, but sometimes that breaks other functions. So it would be nice if you could find a different implementation of escapehellarg or make your own.

Im reffering to 
https://github.com/rosell-dk/webp-express/blob/master/vendor/rosell-dk/webp-convert/src/Convert/Converters/Cwebp.php#L316

and 

https://github.com/rosell-dk/webp-express/blob/master/vendor/rosell-dk/webp-convert/src/Convert/Converters/Cwebp.php#L319

Other sources
https://www.drupal.org/project/imagemagick/issues/1502924
https://www.php.net/manual/en/function.escapeshellarg.php#99213

**Comment by pointmax** [comment]
same issue here! It's quite a bummer that this hasn't been fixed yet… 
Adding `setlocale(LC_CTYPE, "C.UTF-8");` to `/wod/autoloader.php` fixes the issue temporarily

**Comment by mastef** [comment]
@pointmax Thanks for the fix. Submit a PR?

**Comment by rosell-dk** [comment]
Fixed with the PR
