### ISSUE TITLE
Handle when wp-content folder and/or upload folder is moved

### ISSUE THREAD

**Issue by rosell-dk** [rosell-dk/webp-express#40]
Handling that wp-content or upload folder has been moved out of the wordpress installation folder means that we will have save .htaccess rules in each of these folders.

**Comment by rosell-dk** [comment]
https://codex.wordpress.org/Editing_wp-config.php#Moving_wp-content_folder

**Comment by rosell-dk** [comment]
Btw, it currently works when wp-content is moved somewhere *within* the realm of the .htaccess file in the wordpress installation folder. This issue is about when it is moved out of that folder

**Comment by rosell-dk** [comment]
Done. Took a great deal of effort!

**Comment by rosell-dk** [comment]
It doesn't handle when uploads are moved out of wp-content yet...

**Comment by rosell-dk** [comment]
Is the "https://media.originaldomain.tld/content/" on a CDN? Then it should work, as long as the CDN forwards the Accept header.

**Comment by Desdecado** [comment]
Unfortunately not. When I created the site I set up a subdomain to handle all medias for a number of reasons.
But the .htaccess file is in the correct place, it just has  lines like this:
RewriteCond %{DOCUMENT_ROOT}/wp-content/$1.$2.webp -f

Should it not be possible to exchange the "wp-content" bit with data from the media-settings page in Wordpress?

**Comment by rosell-dk** [comment]
I wasn't even aware that it was possible to change the upload *url* path. It is not mentioned here: https://codex.wordpress.org/Editing_wp-config.php#Moving_uploads_folder. But it seems there is an option for it called "upload_url_path" in the options table.

I cannot see any settings related to this on the media settings page? (Settings > Media)

**Comment by Desdecado** [comment]
At the bottom of the media settings screen I've set my new path:
![image](https://user-images.githubusercontent.com/46559281/50961997-87c00080-14c9-11e9-933a-f5cf724279ed.png)

**Comment by rosell-dk** [comment]
Which version of Wordpress are you on? 
It seems the option to set upload path and url path was removed in Wordpress 3.5: https://www.itnota.com/change-wordpress-upload-folder/

**Comment by rosell-dk** [comment]
Being that the option to change upload URL path has been removed in Wordpress 3.5, I guess the setup where the URL is changed is very uncommon. So other issues and features are prioritized over this one.

When the Bulk convert feature becomes available, you can use the "Just convert" operation mode. Right now, with "Just convert", you will have to use Cache Enabler or ShortPixel for altering the HTML, but I'm currently working on providing that functionality directly in WebP Express.

**Comment by Desdecado** [comment]
Strange, I've used these settings for many wordpress sites over the years and all of them are always at (and constantly upgraded) to the latest version.

The site where I have this problem is WordPress 5.0.3 (updated yesterday)

**Comment by rosell-dk** [comment]
Ok. I have created a new issue for this (#148). This issue was about handling a modified file path for uploads, and that works. The new issue is about handling modified URL for uploads. Right now I'm very focused on the next release. I shall look at this when it fits in.
