### ISSUE TITLE
Options Resetting to Defaults

### ISSUE THREAD

**Issue by stallionseo** [rosell-dk/webp-express#411]
The options are resetting, pretty sure the options are resetting to the defaults.

For example a few days ago under "Conversion method" I have one active method available, so I moved that method to the top and deactivated all other methods for better server performance.

That change has been reset at least twice on one of my sites, the available method is at the bottom of the list (I moved it to the top).

I have a sub-domain on the same domain which I set to the same settings at the same time, so far that's not been reset. Only difference between the main domain and sub-domain is the main domain uses W3 Total Cache,

Any thoughts on what could trigger the options to reset?

**Comment by marcissimus** [comment]
might be related to a firewall preventing updates to /wp-content/webp-express

**Comment by mcance** [comment]
I have the same issue that looks like a common problem: https://wordpress.org/support/topic/settings-changes-resets-automatically/

All the plugin’s tests pass, conversion settings added, config saved. Rewrite rules are correctly added and WebP images served.

Then sometime later WebP images are no longer served. Visit the plugin’s settings and they have defaulted: ‘Conversion’ settings’ display the default values and ‘Alter HTML’ is disabled.

I will make some time to trawl through the logs and update with any findings. The only cause that would immediately spring to mind is some other plugin overwriting WebP’s .htaccess mods.

**Comment by marcissimus** [comment]
I was wrong. Most likely related and fixed here:
https://github.com/rosell-dk/webp-express/commit/f6314fc9fc66e8ccf4032eacf1ccced768258be3

Not included in the plugin yet but targeted for 0.17.4. I have no idea when that will become public but you can change this one line yourself if you like.

**Comment by mcance** [comment]
Patched and testing now. Will report back.

**Comment by rosell-dk** [comment]
Thanks, both of you. I shall release when I hear from @mcance

**Comment by mcance** [comment]
Ran all through the weekend with no issues. Fantastic plugin.

**Comment by rosell-dk** [comment]
Released in 0.17.4. Sorry for the long delay!
