### ISSUE TITLE
Alter HTML unchecking 

### ISSUE THREAD

**Issue by frankmassivejoes** [rosell-dk/webp-express#414]
We are finding that the Alter HTML box is unchecking and therefore causing images not to load properly on some devices. We think this might be happening when the website and or plugins are being updated so we have to keep checking that the Alter HTML box is checked regularly. Has anyone else experience something like this and know how to fix it?

**Comment by neevalex** [comment]
Hi! yes i am getting the same issue each few days. Very frustrating, and i have to manually check this option each single day. 

Is there any way to force this option?

**Comment by rosell-dk** [comment]
I believe the problem was related to #397. If so, it should work now, in 0.17.4, which has just been released.
