### ISSUE TITLE
Cache-Control header being reset every few days

### ISSUE THREAD

**Issue by bobhuf** [rosell-dk/webp-express#419]
Hi,

My Cache-Control header setting is being reset every few days. My host has indicated he isn't doing anything to the htaccess file. What can be causing this? I'm using W3 Total cache as well, could that be interfering?

Thanks.

**Comment by bobhuf** [comment]
Anyone? This keeps happening.

**Comment by rosell-dk** [comment]
It is probably due to #397. I shall release soon.

**Comment by rosell-dk** [comment]
Fixed

**Comment by bobhuf** [comment]
Much appreciated!
