### ISSUE TITLE
A great configuration not yet reported (LiteSpeed Cache + BunnyCDN)

### ISSUE THREAD

**Issue by ribeiroeder** [rosell-dk/webp-express#433]
Hello @rosell-dk

I would like to share a new (and great) configuration that deserves a review of the plugin usage explanations.

I'm using LiteSpeed Cache + BunnyCDN together with the configuration of your plugin in "Replace image URLs" and "Only do the replacements in webp enabled browsers" mode.

So far I have not identified any BUG, LiteSpeed Cache can work with separate caches for browsers without WebP support. You need to enable an option below.

![LiteSpeed](https://user-images.githubusercontent.com/24439523/89704577-49035e00-d92b-11ea-9caa-9f98119d29ec.jpg)

And on bunnyCDN just check an option that also allows you to separate cache requests for browsers with and without WebP support.

![Cache-bunnyCDN](https://user-images.githubusercontent.com/24439523/89703983-70a3f780-d926-11ea-853c-26207987870d.jpg)

This makes the part that explains that: "this way of working the plugin is not compatible with cache" becomes partially incorrect. In addition to mentioning the Cache Enabler Plugin, it is worth mentioning LiteSpeed Cache. And for CDN's I don't know any options like the one offered by bunnyCDN.

Thanks for this great plugin!

**Comment by ribeiroeder** [comment]
Some more important notes:

- As far as I could see LiteSpeed Cache just adds those lines to the .htaccess

![htaccess](https://user-images.githubusercontent.com/24439523/89704648-ffffd980-d92b-11ea-8532-0588814cb956.jpg)

- LiteSpeed Cache has an option to generate webp files on demand when uploading. This option should not be checked, it is not very functional and is not suitable for images cropped on the fly, theme images and plugins images.

**Comment by ribeiroeder** [comment]
More info about liteSpeed Cache option "Image WebP Replacement"

https://docs.litespeedtech.com/lscache/lscwp/imageopt/#image-webp-replacement

**Comment by ribeiroeder** [comment]
![OptionsLiteSpeed](https://user-images.githubusercontent.com/24439523/89706256-43614480-d93a-11ea-90e3-bf1b405a3f7c.jpg)

^ Print of LiteSpeed Cache complete Config:

1. Create WebP Versions = OFF 
After all, the one who will take care of this is Webp-Express.

2. Image WebP Replacement = ON 
This option enables the cache separations of browsers with and without WebP support.

3. WebP Attribute To Replace.
I just left a meaningless value for my pages, this prevents both plugins from working by rewriting the html

**Comment by rosell-dk** [comment]
Ok, thanks for sharing! I shall look at it more closely and add it to the FAQ

**Comment by rosell-dk** [comment]
@ribeiroeder, I'm about to add this to the FAQ: Do you have any comments?

### I am on a Litespeed server
If you are on a Litespeed server, you can use the `LiteSpeed Cache` plugin for separate page caches (one for browsers that supports webp, one for browsers that don't). The setup was kindly shared and explained in detail by @ribeiroeder here: https://github.com/rosell-dk/webp-express/issues/433

**Comment by ribeiroeder** [comment]
@rosell-dk I always used the option "Varied image responses" with liteSpeed, and I never had any problems, not even when I activated bunnyCDN.

**Comment by ribeiroeder** [comment]
### I am on a Litespeed server

You do not have to do anything special for it to work on a Litespeed server. You should be able to use WebP Express in any operation mode. For best performance, I however recommend that use the LiteSpeed Cache plugin for page caching. 

LiteSpeed Cache can be set up to maintain separate page caches for browsers that supports webp and browsers that don't. Through this functionality it is possible to use "Alter HTML" with the option "Replace image URLs" and "Only do the replacements in webp enabled browsers" mode.

The setup was kindly shared and explained in detail by ribeiroeder here: [#433](https://github.com/rosell-dk/webp-express/issues/433)

**Comment by rosell-dk** [comment]
its published

**Comment by ribeiroeder** [comment]
@rosell-dk If you need access to a test setup on a litespeed + litespeed cache server, return it to me as I would like so that I can provide it. Thank you

**Comment by ribeiroeder** [comment]
@rosell-dk If you need access to a test setup on a litespeed + litespeed cache server, return it to me.  I can create a clean installation in my test domain, in a sub directory that only you will have access to.

Thanks!

**Comment by rosell-dk** [comment]
@ribeiroeder That would be much appreciated. Thanks! You can write to me at it@rosell.dk

**Comment by lippopippo** [comment]
Hi @ribeiroeder ,
very interesting....one question....how do you connect to bunny cdn? using their plugin or through litespeed cahe?

thanks

**Comment by ribeiroeder** [comment]
hi @lippopippo

I connected bunnyCDN directly from Litespeed Cache:

1 - CDN Settings > Use CDN Mapping > **ON**

![1](https://user-images.githubusercontent.com/24439523/90845523-98d72180-e33c-11ea-95e6-c48b3ebf322b.jpg)

2 - CDN URL > Include https://**yourPullZone**.b-cdn.net/

![2](https://user-images.githubusercontent.com/24439523/90845616-c58b3900-e33c-11ea-9305-9a5f438d910c.jpg)

3 - Include File Types > Include **.webp**

![3](https://user-images.githubusercontent.com/24439523/90845717-01260300-e33d-11ea-9854-bbaf612e87e6.jpg)

4 - Original URLs > Include //**yourdomain**.com/

![5](https://user-images.githubusercontent.com/24439523/90845943-85788600-e33d-11ea-903a-75b2d2f670aa.jpg)

5 - In the Web Express plugin config > CDN hostname(s) / hostname alias(es)  > Include **yourPullZone**.b-cdn.net/

**Comment by stefanmm** [comment]
@ribeiroeder Thanks for sharing! Could you please update your [answer](https://github.com/rosell-dk/webp-express/issues/433#issuecomment-670846547) for the newest plugin version v6.1? Some options are added and some are removed since.
Also, can you recommend the setup without BunnyCDN? Specifically LiteSpeed cache plugin + webp-express + Cloudflare (free). Thanks.
