### ISSUE TITLE
Add ability to set "%{DOCUMENT_ROOT}" part of RewriteCond

### ISSUE THREAD

**Issue by mirekdlugosz** [rosell-dk/webp-express#459]
Some hosting providers don't update `%{DOCUMENT_ROOT}` for user domains. Wrong path will cause RewriteCond rule to not match, which in turn will result in redirect not taking place, leaving user puzzled why plugin is not working as expected.

For example, on Ionos / 1and1 `%{DOCUMENT_ROOT}` points to `/var/www/html`. Users should instead use `%{ENV:DOCUMENT_ROOT}`, which points to correct directory: `/kunden/homepages/<id>/htdocs/<site>`.

[This StackOverflow user](https://stackoverflow.com/q/9153262/3552063) claims he needed to use `%{ENV:DOCUMENT_ROOT_REAL}` to get correct path.

I managed to solve my problem, but I'm worried my fix will be rolled back on plugin update. I would highly appreciate if there was a way to use custom value in place of `%{DOCUMENT_ROOT}` in RewriteCond entry, so I could account for quirkiness of my hosting provider in permanent and safe manner.  

Personally I don't need UI for that, setting constant in wp-config.php (or whenever) would be completely fine, as long as it is documented somewhere.

Thank you very much for great work on amazing plugin!

**Comment by rosell-dk** [comment]
Hi,

Yes, manual edits in the WebP Express block in the .htaccess file may be overwritten upon save and also upon plugin updates.

I'm wondering if we can safely assume that it would always be appropriate to use the DOCUMENT_ROOT environment variable if it is available... ?

**Comment by rosell-dk** [comment]
WebP Express has a "destination structure" option that allows you to select between "Document root" and "Image roots". If you select the latter, there will be no references to `%{DOCUMENT_ROOT}` in the generated *.htaccess* files.

So changing that option to "Image roots" should solve the problem.

I see that the option defaults to "Document root". But if there are these problems with Document root, I guess I should change the default to "Image roots".

**Comment by rosell-dk** [comment]
Does these suggested changes solve it for you, or is there still a need for changing the value? I have actually implemented a way to have WebP Express use something other than "%{DOCUMENT_ROOT}" in .htaccess. But if there is no actual need for such thing, I guess I should not commit this

**Comment by rosell-dk** [comment]
I'm eager to release now, so I release the possibility to set a different document root even though I'm not sure you need it.

Usage:
`
define( 'WEBPEXPRESS_DOCUMENT_ROOT_IN_HTACCESS', '%{ENV:DOCUMENT_ROOT}' );
`

**Please tell me if you need it. If nobody reacts to this and tells me they need it, I might consider removing the feature again.**

**Comment by rosell-dk** [comment]
Just released 0.18.3

**Comment by mirekdlugosz** [comment]
@rosell-dk thanks for your replies.
I'm sorry to report that switching Destination structure to "Image roots" did not help. Apart from one generated by plugin, I tried various RewriteCond combinations and modifications, but I never managed to get webp file in response. Following line is the only one that consistently works on this hosting provider:
```
RewriteCond %{ENV:DOCUMENT_ROOT}%1\.webp -f
```

I very much appreciate quick release of patch solving this problem. That's great!

It would be very welcome if you decide to keep 7a14ea52c61ebb3b62df0b52b19350c41f1ee0c6 around, but I will understand if you decide that this special case is too much maintenance burden.
