### ISSUE TITLE
Convert using CLI

### ISSUE THREAD

**Issue by quangbahoa** [rosell-dk/webp-express#477]
Hello,

I've website that too much images, it more than 20gigs so I cannot convert using `Bulk Convert` from plugin.  Can I convert using CLI or from Ubuntu command line?

Thanks

**Comment by rosell-dk** [comment]
You do not have to convert everything at once, if you enable one of the options to convert missing images on command (via .htaccess rules). 

I'm working on a new Filemanager interface where it will be possible to bulk convert folders.
I'm also considering to add the possibility to convert "in background".

**Comment by rosell-dk** [comment]
Yes, it is possible to bulk convert from the command line. Just make sure that you put the converted files at the correct location and with the correct file extension.

**Comment by quangbahoa** [comment]
Thanks for your support.
