### ISSUE TITLE
[question] network inspector shows type webp, but file transferred is .jpg

### ISSUE THREAD

**Issue by rwkyyy** [rosell-dk/webp-express#496]
Hi there, I am testing on an NGINX configuration, all good ti'll I hit alter HTLM (enable/disable).

When I hit alter HTML, I see the files getting transfered in the network tab with "type webp", when I disable alter html, I do not se the files but I still see the "type: webp".

So, if the type is webp, but the file is the .jpg, why does the network inspector show webp?

p.s. Kinsta cache (proprietary caching plugin) supports alter html as cache.

**Comment by rosell-dk** [comment]
Yes, I get this question frequently.

If you have enabled redirecting (in your case with Nginx rewriting), the jpeg will be redirected to the webp. However, it is an *internal* redirect, which means that the URL will not change. So if for example, the URL ends with ".jpg", it will still end with ".jpg". However, the internal redirect serves you a webp. Now, how does the browser know if it is a jpg or a webp or what? Does it look at the URL? NO! URLs does not carry that information, even though to us humans, it seems to do. The browser determines the type by examining the Content-Type header, which will be webp if the internal redirect was applied. And it does, as your Network inspectior says it is webp.

See also the FAQ:  https://wordpress.org/plugins/webp-express/#how%20can%20a%20webp%20image%20be%20served%20on%20an%20url%20ending%20with%20%22jpg%22%3F

PS: Does *Kinsta cache* work well with WebP Express? (Is it worth mentioning in the FAQ?)
