### ISSUE TITLE
WordPress 5.8 adds WebP support

### ISSUE THREAD

**Issue by bobhuf** [rosell-dk/webp-express#497]
https://make.wordpress.org/core/2021/06/07/wordpress-5-8-adds-webp-support/

Will there be any consequences for WebP Express users?

**Comment by rosell-dk** [comment]
OMG

**Comment by bobhuf** [comment]
Yes, now what will you do with your life? :D

**Comment by zero4281** [comment]
It still doesn't convert images to WebP automatically or allow a single WordPress install to act as an image CDN.

**Comment by Hube2** [comment]
From what I read it only lets you upload WebP images and they are only going to explore other options, so right now you have to decide to server WebP and not support other browsers or continue to use JPG and PNG. Maybe I read it wrong, but that's what I got out of it.

Support seems spotty at best.

They are pushing a different plugin for conversion :(

Plus we'll never get out clients to upload WebP images. We can't event get most of them to understand when they should use JPG vs PNG images.

Until WP auto converts uploads and modifies the HTML correctly, as this plugin does, this plugin still has a purpose, so I hope your not going to give up on this right away.

**Comment by rosell-dk** [comment]
Yeah, the "WebP support" is going to be very minimal in 5.8.
- Wordpress 5.8 allows you to upload webp images (but only if you have either Gd installed with webp support, or Imagick)
- It also allows you to work with webp in the Image Editor
- And it added a hook, which allows you to set webp as your default format. If you do that, images will be converted to webp upon upload.

So WebP Express still have a lot to offer:
- More converters
- More converter options
- More ways to trigger conversion besides on upload: Bulk Convert, Through WP-CLI and on-need-basis (through rewrite rules). A sleek file manager interface for converting single files / folders is under development.
- It is not limited to the "uploads" folder
- Generating rewrite rules for serving webp to webp-enabled browsers.
- Alter HTML functionality as an alternative to using rewrite rules

I just tested Wordpress 5.8 release candidate 2 and it works fine with current WebP Express release.
