### ISSUE TITLE
Add WP CLI command for convert

### ISSUE THREAD

**Issue by rosell-dk** [rosell-dk/webp-express#498]

**Comment by rosell-dk** [comment]
Already completed by @ratnayake:
https://github.com/rosell-dk/webp-express/pull/492

@vasikgreif created something very similar here, but with progress bar:
https://wordpress.org/support/topic/wp-cli-suport-for-bulk-convert/#post-14561675

I think I'll go with the PR, though

**Comment by rosell-dk** [comment]
Adding annotations...
https://make.wordpress.org/cli/handbook/references/documentation-standards/

**Comment by rosell-dk** [comment]
You can use the --help option to learn about the options:
`wp webp-express --help`. Displays the available commands
`wp webp-express convert --help`. Displays the available options for the "convert" command.

A few examples:
`wp webp-express convert`: Creates webp images for all unconverted images
`wp webp-express convert --reconvert`: Also convert images that are already converted
`wp webp-express convert themes`: Only images in the themes folder
`wp webp-express convert --only-png`: Only the PNG images
`wp webp-express convert --quality=50`: Use quality 50 (instead of what was entered in settings screen)
`wp webp-express convert --quality=50`: Use quality 50 (instead of what was entered in settings screen)

`wp webp-express flushwebp`: Remove all webp images
`wp webp-express flushwebp --only-png`: Remove all webp images that are conversions of PNG images

I'm considering adding commands for viewing status, viewing conversion stats, generating the .htaccess files and modifying the settings. Please let me know if you need any of these or perhaps something else.

**Comment by vasikgreif** [comment]
Very cool, thanks!

**Comment by rosell-dk** [comment]
Just published (0.20.0)
