### ISSUE TITLE
Animated PNG (css background) Converts to Static WebP, unable to skip image with query parameter

### ISSUE THREAD

**Issue by anobjectn** [rosell-dk/webp-express#504]
I have a pseudo element with a CSS background that happens to be an animated PNG
https://etc.com/wp-content/uploads/etc/ipad_swivel_temp_small_opt.png?dontreplace=true ('etc' just to shorten example). This is specified in an in-page <style>

The plugin replaces the image with a webp that has no animation. I had expected that adding the query parameter would exclude this image and allow my animated version to remain but instead I see the static webp.

Is there anything else I can do to keep my animated png working and still use WebP Express plugin?

**Comment by rosell-dk** [comment]
Hi,
I don't think there ever been a "dontreplace" query parameter in WebP Express? Have you seen such in some other plugin?
Anyway, in 0.22.0, I added support for skipping replacement.

I actually added two ways to skip replacement.
1) You can add ?original in the querystring. Works both for redirection and Alter HTML
2) You can placing a dummy ".do-not-convert" file next to the original. The name of the file should be the same as the png, but with ".do-not-convert" appended. Only works for redirection (this was unintentional - I will make that work for Alter HTML too in the next release)

Related issues:
- https://github.com/rosell-dk/webp-express/issues/530
- https://github.com/rosell-dk/webp-express/issues/522
- https://github.com/rosell-dk/webp-express/issues/535

**Comment by rosell-dk** [comment]
I must say "dontreplace" is a better name than "?original" and ".do-not-convert"...

**Comment by rosell-dk** [comment]
I am actually going to change the names: https://github.com/rosell-dk/webp-express/issues/536
