### ISSUE TITLE
domain sharding and this plugin

### ISSUE THREAD

**Issue by Hube2** [rosell-dk/webp-express#508]
This is more of a question than an issue.

I have several sites where I have implemented domain sharding. 

Just in case you don't know what it is... basically I alter the src value of all image files as well as other static resources to a sub domain like "static.hostname.com". Actually there are several static  sub domains to split up the requests for images across them. This also results it these resources being served cookie-less.

So my question is, it there any possibility that I can use this plugin in unison with what I am already doing?

I'm looking to increase performance of this site. Just curious if I will need to remove what I have in place to see if I can get better performance using webp images. I'm not worried about replacing one with another as I'll see which give the best performance, but I would like to use them together if at all possible.

**Comment by rosell-dk** [comment]
The images needs to be physicaly on the same server as Wordpress in order to convert images. They don't need to be on the same domain. You should use the "CDN friendly" operation mode. You should enable Alter HTML and the bottom of the settings screen, you can enter the domain name in the "CDN hostname(s) / hostname alias(es)" field.

**Comment by Hube2** [comment]
Sorry I didn't come back here. I did find the hostnames setting after I posted this. But since I have decided to remove domain sharding from the sites still using it. It was a good technique for improving performance but I have recently found that it is bad for mobile performance.  We have started setting up CDNs for most sites now so the hostname settings will still be needed.
