### ISSUE TITLE
Old style htaccess does not work anymore

### ISSUE THREAD

**Issue by utrenkner** [rosell-dk/webp-express#532]
We use the [H2O webserver](https://github.com/h2o/h2o) with your great plugin - many thanks for your superb work! A small Ruby-script makes the necessary translations that are performed via the .htaccess file when using Apache. Today the on-demand conversion by WebP Express stopped working, after upgrade to 0.22.

I was able to track down the cause, and I believe it does not apply to us only: The issue is in `/lib/classes/WodConfigLoader.php`

For us the [fallback in Lines 135-152](https://github.com/rosell-dk/webp-express/blob/master/lib/classes/WodConfigLoader.php#L135-L152) applies. The last line of code reads:
`$wpContentDirRelToWEPluginDir = $wpContentDirRelToPluginDir . '/webp-express';`

For us `$wpContentDirRelToWEPluginDir` evaluates to `..//webp-express`.

However, [in L160 another '/webp-express' is added](https://github.com/rosell-dk/webp-express/blob/master/lib/classes/WodConfigLoader.php#L160) to the path, making `$webExpressContentDirAbs`  `/path/to/my/wordpress/wp-content/plugins/webp-express/..//webp-express/webp-express`, which cannot be found.

I will update our little Ruby script to reflect the new .htaccess style as of 0.22. But maybe you want to fix this problem, because it might also affect people using webservers other than Apache?

**Comment by rosell-dk** [comment]
ahh, whoops! Thanks for notifying me! I will deal with this as soon as I have time

**Comment by rosell-dk** [comment]
Fixed and released as 0.22.1

**Comment by rosell-dk** [comment]
Actually, this bug also caused trouble on Apache servers, as the updating .htaccess doesn't take immediate effect on all servers.
https://wordpress.org/support/topic/error-with-last-update-4/
