### ISSUE TITLE
Update Description Plugin Version 0.25.0 -> 0.25.1 

### ISSUE THREAD

**Issue by yogarasu** [rosell-dk/webp-express#556]
Thank you for the good plugin.

It's a trivial matter, so you can ignore it, but I'll report it just in case.

The version described on the plugin site is different from the version actually downloaded.
The version of the plugin displayed is 0.25.0, but the actual downloaded version is 0.25.1.
https://wordpress.org/plugins/webp-express/#description
<img width="1044" alt="スクリーンショット 2022-02-04 1 59 25" src="https://user-images.githubusercontent.com/68766032/152391138-e1839a35-665b-446e-92a5-338c65019757.png">

**Comment by rosell-dk** [comment]
Thanks!
