### ISSUE TITLE
New update and Cyrillic

### ISSUE THREAD

**Issue by Cruglk** [rosell-dk/webp-express#561]
Hello! Due to a new update, title/alt in images no longer display correctly in Cyrillic text. The problem is in the line:

    $charset = preg_match('//u', $html) ? 'UTF-8' : 'ISO-8859-1';

The previous option worked fine:

    if (function_exists("mb_convert_encoding")) {
      $html = mb_convert_encoding($html, 'HTML-ENTITIES', 'UTF-8');
    }

Example text:

    Это текст для тестирования

**Comment by rosell-dk** [comment]
Ok, sorry and thanks! 
I'll revert.

Unfortunately, mb_convert_encoding is deprecated in PHP 8.2, so I will have to find an alternative soon.
Here is the issue: https://github.com/rosell-dk/dom-util-for-webp/issues/33

**Comment by rosell-dk** [comment]
I have found an alternative to the original code, which doesn't trigger the warning. It is committed in the library and will be part of next WebP Express release.

**Comment by rosell-dk** [comment]
Fixed and released as 0.25.4.
