### ISSUE TITLE
PHP 8.1+  ErrorException Warning: Undefined variable $filePath

### ISSUE THREAD

**Issue by portalzine** [rosell-dk/webp-express#587]
/wp-content/plugins/webp-express/lib/classes/Mime.php in WebPExpress\Mime::getMimeTypeOfMedia at line 39

```

 if (function_exists('wp_check_filetype')) { // introduced in 2.0.4
            // Try wordpress method, which simply uses the file extension and a map
            $mimeType = wp_check_filetype($filePath)['type'];
            if ($mimeType !== false) {
                return $mimeType;
            }
        }
```

ErrorException  happens, when uploading files through the update system (themes or plugins)
Cheers
Alexander

**Comment by gerasart** [comment]
i think need fix  $filePath -> $filename

**Comment by rosell-dk** [comment]
Thanks for [the PR](https://github.com/rosell-dk/webp-express/pull/595), @gerasart !
It will be part of the next release, which won't be long
