### ISSUE TITLE
Warning with PHP 8.2

### ISSUE THREAD

**Issue by Olwyne** [rosell-dk/webp-express#590]
Hello, 

There is some warning for deprecated code with PHP 8.2.

![image](https://github.com/rosell-dk/webp-express/assets/46401913/0d467d5f-5d87-4253-87cc-10abe180f4d3)

Thanks

**Comment by rosell-dk** [comment]
Fixed by @robmeijerink in [this pull request](https://github.com/rosell-dk/webp-express/pull/594)
I'm going to create a new release soon
