### ISSUE TITLE
Nginx rule is not work for my blog. Need help you.

### ISSUE THREAD

**Issue by jun-dev** [rosell-dk/webp-express#61]
Plesa add suppor GIF images to you plugin. Can I try to add support for this tool by analogy with gif? If so, in which file is the shell_exec accessed?

**Comment by rosell-dk** [comment]
In regards to your question about `shell_exec`, it is in the [webp-convert](https://github.com/rosell-dk/webp-convert/) library. In the 0.5.0 version, it has been compiled into `wod/webp-on-demand-1.inc` and `wod/webp-on-demand-2.inc`. In the master version (and the upcoming 0.6.0) here on github, you need to do a `composer install` to get it. In the Wordpress svn, I am going to add the vendor library created by composer, containing the webp-convert library. `shell_exec` is only used by the `cwebp` converter. That source file is here: https://github.com/rosell-dk/webp-convert/blob/master/src/Converters/Cwebp.php

**Comment by jun-dev** [comment]
Thank you for a really useful plugin.
> I found no problems.
Yes, this rule is correct. The error was different.
> In the Wordpress svn, I am going to add the vendor library created by composer, containing the webp-convert library. `shell_exec` is only used by the _cwebp_ converter
As far as I know, the GD built-in PHP library does not convert GIF animation into WEBP format. So most likely you will have to use gif2webp for this.

Also, is it possible to change the storage path of the generated .webp images in the same folder? I mean exclude this path / wp-content / webp-express / webp-images / doc-root / wp-content / and manually change it to / wp-content / *.

**Comment by rosell-dk** [comment]
The Nginx rules stated earlier in this thread are problematic.
Go here for rules: https://wordpress.org/support/topic/nginx-rewrite-rules-4/#post-10982426

**Comment by rosell-dk** [comment]
@jun-dev: I have created an option for storing in same folder: #104. It will be part of the next release (0.10.0). GIF support is longer down the line and is discussed in #62
