### ISSUE TITLE
Call to undefined function WebPConvert\Converters\array_column()

### ISSUE THREAD

**Issue by im2shae** [rosell-dk/webp-express#89]
Fatal error: Call to undefined function WebPConvert\Converters\array_column() in .../wp-content/plugins/webp-express/vendor/rosell-dk/webp-convert/src/Converters/ConverterHelper.php on line 79

**Comment by rosell-dk** [comment]
It seems you are on an old version of PHP. Correct? 
array_column() should be available from PHP >= 5.5, according to [the docs](https://secure.php.net/manual/en/function.array-column.php).

You can for example check PHP version with [this plugin](https://wordpress.org/plugins/debug-info/). I'd very much like to have confirmed that this is the issue.

**Comment by im2shae** [comment]
You are correct, once upgraded the PHP version the error went away. Thank you
