### ISSUE TITLE
Add last-modified header

### ISSUE THREAD

**Issue by lukapaunovic** [rosell-dk/webp-express#90]
In addition to **addCacheControlHeader** function in **/wp-content/plugins/webp-express/vendor/rosell-dk/webp-convert/build/webp-on-demand-1.inc**
we need function for adding last-modified header

Something like

$lastModified=filemtime($this->destination);
header("Last-Modified: ".gmdate("D, d M Y H:i:s", $lastModified)." GMT");

**Comment by lukapaunovic** [comment]
@rosell-dk Do you mind implementing this so scoring tests don't scream for it?

**Comment by rosell-dk** [comment]
Ok, I'm on it [over here](https://github.com/rosell-dk/webp-convert/issues/86)

**Comment by rosell-dk** [comment]
It's implemented in WebP Convert. It requires no change in WebP Express here on github, because vendor files aren't here. They are on svn, and will be pushed there on the next release.

I would like to have more new features / improvements ready before pushing a new release, as I do not wish to overwhelm users by updating the plugin too frequently .

**Comment by lukapaunovic** [comment]
Good to know. I love the plugin, it's a piece of art.
I get the thing about updates, but for instance, if someone had normally working last modified header, and it's just ditched. I spent an hour searching what's wrong (CDN, web server....) when I remembered this plugin was outputting the headers :D

**Comment by rosell-dk** [comment]
I see. I'll will not to wait too long with the next release, then.
Thanks for the nice words and the PR. Didn't notice it before you closed it though :/

**Comment by lukapaunovic** [comment]
Hey mate, sorry for my intrusion again, another slight suggestion, instead of htaccess hitting php each time image is requested you should establish some kind of cache :) 
So only if a converted image doesn't exist in cache THEN to hit PHP and convert. 
High traffic sites converting images with each request is tough on small hostings.

**Comment by rosell-dk** [comment]
Yes indeed. Not having implemented it yet has been on my bad conscience a while... But it will be the next feature, and its on the roadmap for 0.9.0. It will be implemented with .htaccess rules. #100.

I'm by the way planning to release 0.8.0 today. It just needs a little more testing
