### ISSUE TITLE
destination path?

### ISSUE THREAD

**Issue by puggan** [rosell-dk/webp-express#96]
Is there a reason to have `$destination = $imageRoot . '/doc-root' . $sourceRel . '.webp';`
https://github.com/rosell-dk/webp-express/blob/602832e2280e078aee9a228406d930c042725b23/wod/webp-on-demand.php#L56

instead of using `$destination = $imageRoot . '/doc-root/' . $sourceRel . '.webp';`?

Whould be nicer if all images end up in the /doc-root/ folder, then like now, making alot of folders starting with doc-root.

Exemple:
`webp-express/webp-images/doc-rootuploads/puggan.jpeg.webp` (now)
vs
`webp-express/webp-images/doc-root/uploads/puggan.jpeg.webp` (prefered by me)

**Comment by rosell-dk** [comment]
Do you have such folders created on your system?
Then it is an error.
I do not have a lot of folders starting with "doc-root" on any of my test systems. There is just the "doc-root" folder

**Comment by puggan** [comment]
So in your cases, `$sourceRel` always starts with an `/`?

**Comment by rosell-dk** [comment]
Paths are fixed, so closing.

But file structure needs to be cleaned up on systems where there was a missing "/". Creating a new issue for that.

**Comment by cantoute** [comment]
> Paths are fixed, so closing.
> 
> But file structure needs to be cleaned up on systems where there was a missing "/". Creating a new issue for that.

Pardon me if I'm wrong, but I believe it's the other way around.
Seems to me we should assume DOCUMENT_ROOT has no trailing slash.

As it comes from web server configuration.
In apache default settings it has no trailing slash (same in nginx)

```apache
DocumentRoot /var/www/html
```
And on cases it would have been set with a trailing slash by admins, having a double slash referencing over a filesystem is seemless.

```sh
$ cat /etc//issue
Debian GNU/Linux 9 \n \l
```

**Comment by rosell-dk** [comment]
The code is neither assuming that DOCUMENT_ROOT ends with a slash or that it does not. the *$applicationRoot* variable is only used in a few lines.

**Comment by cantoute** [comment]
> systems where there was a missing "/".

I see it that $applicationRoot should not have a trailing slash ;)

**Comment by rosell-dk** [comment]
In this case it works fine. But the code will become easier to read, if I change. So, I shall change.
